//! # TreeItemDTO
//!
//! Defines the Data Transfer Object for a single item in a tree view.

use serde::{Deserialize, Serialize};
use serde_json::Value;

/// A serializable struct that represents a `vscode.TreeItem`.
/// This DTO is sent from `Cocoon` (where the `TreeDataProvider` logic lives)
/// to `Mountain` (where the UI state is managed) to describe how to render an
/// item in a tree view. It uses `serde_json::Value` for complex properties to
/// maintain flexibility and compatibility with the VS Code API.
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct TreeItemDTO {
	/// A unique handle for this item within its tree view, generated by Cocoon.
	pub Handle:String,

	/// The handle of the parent item, if any.
	#[serde(skip_serializing_if = "Option::is_none")]
	pub ParentHandle:Option<String>,

	/// The label for the tree item. Can be a simple string or a
	/// `TreeItemLabel` object for highlighting.
	#[serde(skip_serializing_if = "Option::is_none")]
	pub Label:Option<Value>,

	/// A human-readable description for the tree item.
	#[serde(skip_serializing_if = "Option::is_none")]
	pub Description:Option<String>,

	/// The URI of the resource represented by this item. Serialized
	/// `UriComponents`.
	#[serde(rename = "resourceUri", skip_serializing_if = "Option::is_none")]
	pub ResourceURI:Option<Value>,

	/// The tooltip to show when hovering over the item. Serialized `string` or
	/// `IMarkdownStringDTO`.
	#[serde(skip_serializing_if = "Option::is_none")]
	pub Tooltip:Option<Value>,

	/// The command to execute when the item is selected. Serialized
	/// `CommandDTO`.
	#[serde(skip_serializing_if = "Option::is_none")]
	pub Command:Option<Value>,

	/// The collapsible state of the item (e.g., None, Collapsed, Expanded).
	/// Corresponds to `vscode.TreeItemCollapsibleState`.
	pub CollapsibleState:u32,

	/// A string that can be used for context-menu visibility (`when` clauses).
	#[serde(skip_serializing_if = "Option::is_none")]
	pub ContextValue:Option<String>,

	/// A path to an icon or a light/dark pair of paths. Serialized
	/// `UriComponents`.
	#[serde(skip_serializing_if = "Option::is_none")]
	pub Icon:Option<Value>,

	/// A `ThemeIcon` identifier (e.g., 'file-code'). Serialized `ThemeIcon`.
	#[serde(skip_serializing_if = "Option::is_none")]
	pub ThemeIcon:Option<Value>,

	/// The state of a checkbox displayed next to the tree item, if any.
	/// Serialized `CheckboxState`.
	#[serde(skip_serializing_if = "Option::is_none")]
	pub CheckboxState:Option<Value>,
}
