[build-dependencies]
serde = { workspace = true }
toml = { workspace = true }

[dependencies]
tauri = { workspace = true, features = [
	"wry",
	"tray-icon",
	"devtools",
	"rustls-tls",
	"compression",
], default-features = false }

async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

[features]
default = []

[lib]
crate-type = ["rlib"]
name = "Common"
path = "Source/Library.rs"

[package]
autobenches = false
autobins = false
autoexamples = false
autotests = false
description = "Common 🧑🏻‍🏭"
edition = "2024"
include = [
	"Source/**/*",
	"LICENSE",
	"README.md",
	"CHANGELOG.md",
	"build.rs",
	"Cargo.toml",
]
license-file = "LICENSE"
name = "Common"
publish = false
repository = "https://github.com/CodeEditorLand/Common"
version = "0.0.1"

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
all-features = true
default-target = "x86_64-unknown-linux-gnu"
targets = [
	"x86_64-unknown-linux-gnu",
	"x86_64-apple-darwin",
	"aarch64-apple-darwin",
]
