[build-dependencies]
serde = { version = "1.0.219", features = ["derive"] }
toml = { version = "0.8.20" }

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }


[features]
default = []

[lib]
crate-type = ["rlib"]
name = "Common"
path = "Source/Library.rs"

[package]
autobenches = false
autobins = false
autoexamples = false
autotests = false
description = "Common 🧑🏻‍🏭"
edition = "2024"
include = [
	"Source/**/*",
	"LICENSE",
	"README.md",
	"CHANGELOG.md",
	"build.rs",
	"Cargo.toml",
]
license-file = "LICENSE"
name = "Common"
publish = false
repository = "https://github.com/CodeEditorLand/Common"
version = "0.0.1"
