/// @module TreeItemDto
/// @description Defines the Data Transfer Object for a single item in a tree
/// view.
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// A serializable struct that represents a `vscode.TreeItem`.
///
/// This DTO is sent from Cocoon (where the `TreeDataProvider` lives) to
/// Mountain (where the UI state is managed) to describe how to render an item
/// in a tree view. It uses `serde_json::Value` for complex properties to
/// maintain flexibility.
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "PascalCase")]
pub struct TreeItemDto {
	/// A unique handle for this item within its tree view, generated by Cocoon.
	pub Handle:String,

	/// The handle of the parent item, if any.
	#[serde(skip_serializing_if = "Option::is_none")]
	pub ParentHandle:Option<String>,

	/// The label for the tree item. Can be a simple string or a `TreeItemLabel`
	/// object.
	#[serde(skip_serializing_if = "Option::is_none")]
	pub Label:Option<Value>, // DTO: string | { label: string, highlights: [number, number][] }

	/// A human-readable description for the tree item.
	#[serde(skip_serializing_if = "Option::is_none")]
	pub Description:Option<String>,

	/// The URI of the resource represented by this item.
	#[serde(skip_serializing_if = "Option::is_none")]
	pub ResourceUri:Option<Value>, // DTO: UriComponents

	/// The tooltip to show when hovering over the item.
	#[serde(skip_serializing_if = "Option::is_none")]
	pub Tooltip:Option<Value>, // DTO: string | IMarkdownStringDto

	/// The command to execute when the item is selected.
	#[serde(skip_serializing_if = "Option::is_none")]
	pub Command:Option<Value>, // DTO: CommandDto

	/// The collapsible state of the item (e.g., None, Collapsed, Expanded).
	pub CollapsibleState:u32,

	/// A string that can be used for context-menu visibility (`when` clauses).
	#[serde(skip_serializing_if = "Option::is_none")]
	pub ContextValue:Option<String>,

	/// A path to an icon or a light/dark pair of paths.
	#[serde(skip_serializing_if = "Option::is_none")]
	pub Icon:Option<Value>, // DTO: UriComponents

	/// An alternative icon for dark themes.
	#[serde(skip_serializing_if = "Option::is_none")]
	pub IconDark:Option<Value>, // DTO: UriComponents

	/// A `ThemeIcon` identifier (e.g., 'file-code').
	#[serde(skip_serializing_if = "Option::is_none")]
	pub ThemeIcon:Option<Value>, // DTO: { id: string, color?: string }

	/// The state of a checkbox displayed next to the tree item, if any.
	#[serde(skip_serializing_if = "Option::is_none")]
	pub Checkbox:Option<Value>, // DTO: CheckboxState
}
